.TH SECRET 1

.SH NAME
secret \- client and server for sending and catching icmp packets with encrypted file.

.SH SYNOPSIS
client \- 
.B sudo ./secret
\fB\-r \fIFILE\fR
\fB\-s \fIIP\fR

.sp
server \- 
.B sudo ./secret
\fB\-l\fR

.SH DESCRIPTION
Program must first be built by make (If using on server Merlin from VUT FIT make merlin).

.B secret (as client)
sends icmp packets with encrypted file specified by argument \fB\-r\fR
to IP given by argument \fB\-s\fR.
.sp
.B secret (as server)
catches icmp packets and checks if it's packet send by client. If so decrypt file in packet and
write it into local directory.

.SH OPTIONS
.TP
.BR \-r
File which is supposed to be encrypted and sent. (client)
.TP
.BR \-s
IP where to send packets. (client)
.TP
.BR \-l
Run as server. If not set, run as client.

.SH EXAMPLES
To send file named \fBtest.txt\fR to local host:
.PP
.nf
.RS
sudo ./secret -r test.txt -s 127.0.0.1
.RE
.fi
.PP

To run server:
.PP
.nf
.RS
sudo ./secret -l
.RE
.fi
.PP

.SH HANDED IN FILES
secret.cpp, secret.1, manual.pdf, Makefile
